version: '2.1'
volumes:
  resin-data: {}
  dashboard: {}
  influx-data: {}
services:
  node-red:
    build:
      context: ./node-red
    volumes:
      - 'resin-data:/data'
    restart: always
    privileged: true
    network_mode: host
    ports:
     - 1880:1880
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
    environment:
      USERNAME: balena
      PASSWORD: balena
      ENCRIPTION_KEY: balena
    devices:
      - '/dev/mem:/dev/mem'
  influxdb:
    image: 'influxdb:1.8.0'
    container_name: influxdb
    restart: always
    environment:
      INFLUXDB_DB: balena
      INFLUXDB_USER: iiot
      INFLUXDB_ADMIN_ENABLED: 'true'
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_DATA_DIR: /data
    volumes:
      - 'influx-data:/data'
    network_mode: host
  grafana:
    image: 'grafana/grafana'
    restart: unless-stopped
    #network_mode: host
    ports:
     - 3000:3000
    volumes:
      - 'dashboard:/data'
  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    network_mode: host
